### ISSUE TITLE
Not able to install reduce through cmake

### ISSUE THREAD

**Issue by QingweiMeng1234** [rlabduke/reduce#38]
Hi,

I am not able to install reduce through cmake. I guess it is probably the version of gcc is too old. I attached the problem down below. 

![image](https://user-images.githubusercontent.com/19242683/128278453-16d5abdb-3a37-4502-b8eb-c3af2a25a8e1.png)

**Comment by russell-taylor** [comment]
In the latest master branch, CMakeLists.txt requested C++ version 11, but did not require it.  I just pushed a commit that adds a flag that should require it, which will presumably refuse to compile with a version of the compiler that does not support C++11.

It should have given you a warning during CMake configure that it was unable to meet the requirement, but now it will fail to generate the build files.  If you can't get a C++11 compiler, you will need to revert to an earlier release.

Let me know what happens when you pull the new commit.

**Comment by QingweiMeng1234** [comment]
I just pulled the newest version and it worked on my server. Thank you!

**Comment by QingweiMeng1234** [comment]
But it seems that it is still not properly installed even if it looks good. Do you know why the server still cannot detect reduce?
![image](https://user-images.githubusercontent.com/19242683/128427697-f40c9c06-1d49-4c0a-bf80-78a0e95dfe1b.png)
![image](https://user-images.githubusercontent.com/19242683/128427738-92958e4a-6258-4e0a-946e-21c654cfd1af.png)
