### ISSUE TITLE
Processing structures with different forms of histidine...

### ISSUE THREAD

**Issue by rwxayheee** [rlabduke/reduce#41]
Dear reduce experts, 

I'm trying to convert a united-atom protein structure into an all-atom structure using reduce. The command I use is: 

`reduce input.pdb -NOFLIP -Keep -DB reduce_wwPDB_het_dict.txt > output.pdb`

In the input pdb structure, I have histidine residues in different forms, including the (delta-protonated), HIE (epsilon-protonated) and HIP (doubly-protonated) philistines. Although the N-epsilon hydrogens (HE2) are given in the input structure, all are turned into the HID form in the output structure. 

I wonder if there's an option to keep the original form of the histidine residues in the given structure, or, if I have to enforce it by using a modified het_dict.txt and different residue names. 

Any comments or suggestions would be greatly appreciated. 

Massive Thanks,
Amy

**Comment by russell-taylor** [comment]
Amy,

So it turns out that -NOFLIP is named a bit misleadingly.  It does the hydrogen addition and then avoids flipping the Histidine rings.  If you avoid passing -HIS, -FLIP, and -NOFLIP on the command line, I think that will do what you want (leave Histidines strictly alone).

Assuming the rest of the command line is doing what you want, I think you want:

`reduce input.pdb -Keep -DB reduce_wwPDB_het_dict.txt > output.pdb`

Thanks,
Russ

**Comment by rwxayheee** [comment]
Hi Russ, 

`reduce input.pdb -Keep -DB reduce_wwPDB_het_dict.txt > output.pdb`
Yes that works out perfectly for me. Thank you so much for your kind advice!! 

Best,
Amy
