### ISSUE TITLE
N-terminal detection too strict

### ISSUE THREAD

**Issue by merkys** [rlabduke/reduce#48]
I am using Reduce v4.7 to add hydrogen atoms to PDB files. In some of the files, residues in protein chains are not numbered from 1, but from some larger integer. I am aware of the reasons why such residue numbering is used, but I still would like to have each initial residue of each protein chain to be protonated as N-terminal. Is there a way to do so?

**Comment by russell-taylor** [comment]
I talked with Jane about this, and basically Reduce should not put a charge on what is probably not actually the N-terminus.  It is too risky to allow this to happen because it would more often be incorrect, so Reduce provides no way to do this.  If you want to do this, you'll have to do the addition outside of Reduce.

**Comment by merkys** [comment]
Thanks for clarification.
